baseURL = 'https://ohyeah2389.github.io'
languageCode = 'en-us'
title = 'Portfolio'
theme = 'LoveIt'
defaultTheme = "dark"

# git repository URL for editing posts
gitRepo = "https://github.com/ohyeah2389/ohyeah2389.github.io"

[params]
  # LoveIt theme version
  version = "0.3.X"

  # site default theme ("light", "dark", "auto")
  defaultTheme = "dark"
  
  # public git repo url only then enableGitInfo is true
  gitRepo = "https://github.com/ohyeah2389/ohyeah2389.github.io"
  
  # App icon config
  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "Portfolio"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = "/img/favicons/favicon.svg"
    # Android browser theme color
    themeColor = "#232323"
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-11 tile color
    tileColor = "#232323"
  
  # site info
  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      logo = ""
      name = "ohyeah2389"
      pre = ""
      post = ""
      typeit = false

  # Footer config
  [params.footer]
    enable = true
    custom = ""
    hugo = true
    copyright = true
    author = true
    since = 2024
    icp = ""
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # Home page config
  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "/img/avatar.jpg"
      title = "Portfolio"
      subtitle = "Information about my work and experience"
      typeit = false
      social = true
      disclaimer = ""
    [params.home.posts]
      enable = true
      paginate = 8
      defaultHiddenFromHomePage = false
      orderBy = "weight"

  # Social config about the author
  [params.social]
    GitHub = "ohyeah2389"
    Email = "ohyeah2389@yahoo.com"
    Youtubecustom = "ohyeah2389-samd"
    Discord = "ohyeah2389"
    Discordinvite = "https://discord.gg/9cv8aeQr6S"
    Instagram = "ohyeah2389"

  # Page global config
  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    twemoji = false
    lightgallery = false
    ruby = true
    fraction = true
    fontawesome = true
    linkToEdit = false
    rssFullText = false
    [params.page.toc]
      enable = true
      keepStatic = false
      auto = true
    [params.page.code]
      copy = true
      maxShownLines = 50
    [params.page.math]
      enable = false
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      copyTex = true
      mhchem = true
    [params.page.library]
      [params.page.library.css]
        custom = "css/custom.css"
    [params.page.share]
      enable = false
      Twitter = true
      Facebook = true
      Linkedin = true
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Flipboard = false
      Weibo = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false
      Diaspora = false
      Telegram = false

# Markup related config
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    pre = ""
    post = ""
    name = "Posts"
    url = "/posts/"
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
  [[menu.main]]
    weight = 4
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""